### ISSUE TITLE
Wrong elements' styles returned to critical sheet

### ISSUE THREAD

**Issue by petulla** [addyosmani/critical#102]
Here is my gulp task:

```
gulp.task('critical-css', function () {
    critical.generate({
        base: './',
        src: 'index.html',
        css: ['./build/style/style.css'],
        htmlTarget: 'index.html',
        dimensions: [{
          width: 414,
          height: 736
        },{
          width: 768,
          height: 1024
        },{
          width: 1280,
          height: 960
        },{
          width: 2560,
          height: 1440
        }],
        dest: './build/style/critical.css',
        minify: true
    });
});
```

I'm not getting anywhere near the style sheet I need outputted from the task, I'm afraid. Is there something obvious I'm missing in the task? I'm seeing absolutely positioned elements well down the page and past the critical rendering path receiving styles while elements at the top's styles aren't outputted in the `critical.css` file.

**Comment by bezoerb** [comment]
@petulla The task configuration looks ok but it's pretty hard investigate your issue without the used html,css and js. Can you post a link to the website you are working on? 

You are using `dest` and `htmlTarget` in your task. Is this just for debugging purpose or are you using both (css & html) in a later step of your build process? I'm asking because we've deprecated the `htmlTarget` and `styleTarget` options and therefore this won't be possible after 1.0.x. If there's a proper usecase for this we might need to think this over.

**Comment by ryanmargheriti** [comment]
I was having the same issue. I found explicitly setting the stylesheet (as well as having it in the html) fixed my problem. 

@petulla I see that you already setting the stylesheet so this won't fix your issue, but might be helpful for others who land on this page.

**Comment by bezoerb** [comment]
Closing this due to lack of feedback. Feel free to reopen if you still got problems on this one.
