### ISSUE TITLE
Why only some of the pseudo classes being added to the critical path ?

### ISSUE THREAD

**Issue by borisirota** [addyosmani/critical#185]
In my use case where I use some pseudo classes `:link, :not, :first-child, :last-child` are being added while `:visited, :active, :focus, :hover` aren't.

Thanks

**Comment by pocketjoso** [comment]
@borisirota [Penthouse](https://github.com/pocketjoso/penthouse) intentionally filters out psuedo selectors that require user interaction, i.e. `:active, :focus, :hover`, in order to keep the critical css as small as possible.

`:visited` should be kept, but I see that it isn't. Can you please create an issue on the Penthouse repo?

**Comment by borisirota** [comment]
Sure. I created [issue 149](https://github.com/pocketjoso/penthouse/issues/149). Thanks !

**Comment by borisirota** [comment]
Fixed !
