### ISSUE TITLE
css tag missing after compiling critical

### ISSUE THREAD

**Issue by SergeyYermak** [addyosmani/critical#187]
Hi.
When i'm compiling critical with gulp, i have transition  css tag missing in result css file.
Maybe I'm doing something wrong - pretty new to gulp and node.
In the source file I have this piece:
`.anim-elem {
  transition: all .8s;
  opacity: 0;
}`
But in critical file I have in result:
`.anim-elem {
  opacity: 0;
}`
Other tags seems ok.

My gulp file that i'm using:
```

var gulp = require('gulp');
var critical = require('critical');

gulp.task('critical', function(cb){
critical.generate({
	    base: './',
	    src: 'toprocess/home.html',
	    dest: 'dist/final.css',
	    minify: false,
	    inline: false,
	    width: 1920,
	    height: 1080
	});
});


gulp.task('default', ['critical'], function(){});

```

**Comment by bezoerb** [comment]
@pocketjoso: is this intended?

**Comment by pocketjoso** [comment]
Yes - it's removed [here](https://github.com/pocketjoso/penthouse/blob/master/lib/index.js#L154).
The idea is that the first render is static - user initiated animations get activated when full css & js loads.

@SergeyYermak - Do you have a use case where it would be relevant for the critical css to contain properties? Remember that these properties will arrive when the full css loads.

**Comment by SergeyYermak** [comment]
@pocketjoso: I have some text at the top of my page. It slides from one side to center when page is opening. But with critical css it just stands still at the center.

**Comment by pocketjoso** [comment]
@SergeyYermak What initiates the slide effect normally? Page opening doesn't trigger any css transitions, you must be adding a class or similar, with js?

**Comment by SergeyYermak** [comment]
@pocketjoso yep, it is some js that initiates it. My code animates elements when they are in the viewport. So the top part of the page needs to be animated from the beginning. It adds css class that changes elements position and opacity (depending on transition property that should be there allready).

**Comment by SergeyYermak** [comment]
It would be nice to have some option to include those removed properties.

**Comment by pocketjoso** [comment]
Critical css is for the first render, which happens before JS. The smaller the critical css the faster the first render can happen, hence why measures like the removal of transition properties are taken.

That being said, we don't want to break anyone's site. The issue in your case must be that your JS loads before your full css, hence initiating this supposed animation before the supporting CSS is there.

My general advise here would be to use a @keyframe animation instead of transition for this effect. A @keyframe animation can happen as soon as the (critical) css loads, without the help of any Javascript (so much sooner) - and is for this reason not removed from critical css. If you're really keen on keeping your code as it is, I'm open for a PR for [Penthouse](https://github.com/pocketjoso/penthouse) to override the default properties (pattern) array for what properties to remove.
