### ISSUE TITLE
Don't modify disabled stylesheets

### ISSUE THREAD

**Issue by midzer** [addyosmani/critical#228]
Hi,
with latest version (0.9.0) `=disabled` is appended to `disabled` attribute in any `link` element.

This breaks its implementation for me under Chromium 59, as those disabled stylesheets are not skipped while page is loading.

According to https://www.w3schools.com/TAGS/att_disabled.asp `disabled` is just used as is, without any appendix.

Cheers
midzer

**Comment by bezoerb** [comment]
Could you give some more insights on your use case? 
I just gave it a small test and the link tags are replaced with the following:

**before critical**
```html
<link rel="stylesheet" href="css/main.css" disabled>
````

**after critical**
```html
...
<link rel="preload" href="css/main.css" disabled as="style" onload="this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="css/main.css" disabled></noscript>
...
```

According to [MDN](https://developer.mozilla.org/docs/Web/HTML/Element/link#attr-disabled) the `disabled` attribute is non-standard and only used by some browsers. So this should not be used anyway. 
Have you considered setting the media attribute for the according stylesheets to something inapplicable to ensure they'll fetch without blocking render instead of using the `disabled` attribute?

**Comment by midzer** [comment]
Basically i wanted to achieve a theme switch by clicking on a button in my website.

First of all, i have a regular `main.min.css` and right below i used a `link` with no `href` and populated its value with JS on button click to have extended css loaded for a new theme. Worked like charm for all tested browsers. Miserably this `link` without `href` resulted in a warning by Chromium 59.

So i tried to put `href=""` making critical crash in one of its depencies (took me quite a while to figure out the involved commit *g*). If you like, i open a seperate issue for this one.

Surfing the web, i stumbled upon `disabled` attribute. Thanks for your link to MDN. I think i have to bookmark this one :+1: 

Contrary to your example, my initial, `disabled` link looks like the following:
`<link rel="stylesheet" id="theme-link" href="SOMEPROPERPATH" disabled>`
resulting in
`<link rel="preload" id="theme-link" href="SOMEPROPERPATH" disabled="disabled">
