### ISSUE TITLE
display: flex gets extracted as display: -webkit-box;

### ISSUE THREAD

**Issue by developer-lindner** [addyosmani/critical#242]
Hey there!

display: flex gets extracted as display: -webkit-box; which breaks the layout.
Any idea how to fix this?

**Comment by pocketjoso** [comment]
@developer-lindner this is due to how [Penthouse](https://github.com/pocketjoso/penthouse) handles invalid original CSS (with syntax errors) - it runs it through a normalisation process that currently goes through Chrome and hence currently drops all properties Chrome doesn't use.

Penthouse can be run with `strict: true` to throw on CSS syntax errors, instead of doing the normalisation - but I don't think this flag is handled in critical. cc @bezoerb 

@developer-lindner If you could run your css through any kind of CSS linter, fix the problems, and run critical again, it should fix this issue for you.

**Comment by developer-lindner** [comment]
@pocketjoso thank you for your fast reply, seems like penthouse 1.0 has almost landed. Will give it a try as soon as it is available!

**Comment by pocketjoso** [comment]
It has landed (last week), you can try it now!

**Comment by developer-lindner** [comment]
@pocketjoso I would.. but the PR is still open and the package.json still has "penthouse": "^0.11.13".

**Comment by bezoerb** [comment]
@developer-lindner: we just released [v1.0.0](https://github.com/addyosmani/critical/releases/tag/v1.0.0). Would you mind to check again with the new version?

**Comment by developer-lindner** [comment]
@bezoerb just tested it yesterday and it works like a charm!
