### ISSUE TITLE
[BLOCKER] Extracted CSS are incomplete after Penthouse update to @1.1.3

### ISSUE THREAD

**Issue by topogigiovanni** [addyosmani/critical#257]
I'm having very different results after reinstalling the Lib Critical with the Penthouse in version 1.1.3. The generated files are considerably different and smaller.

My Node version is v6.10.3

**Comment by pocketjoso** [comment]
Can you try running directly towards Penthouse, and getting incorrect styles, opening an issue there instead? If the issue is coming from Penthouse, most likely you have errors in your original CSS, causing the AST parsing to fail. You can try posting your css into this [AST explorer, on the CSS tab](https://astexplorer.net/) and ensure it can parse your css without any errors - or even better run your CSS through a css linter (I use [stylelint](https://github.com/stylelint/stylelint)) and fix the issue they raise.

**Comment by topogigiovanni** [comment]
Thanks for your suggestions @pocketjoso. Running Penthouse directly in v1.1.3, I have the same wrong result. I will open the issue there. 

I still wonder if other Critical lib users are not experiencing the same problem due to this Penthouse version change. If so would not it be interesting to define the dependency for version v1.1.2?

**Comment by pocketjoso** [comment]
More likely that the problem came from `1.0.0` than specifically `1.1.3` - but let's debug in penthouse repo.

**Comment by topogigiovanni** [comment]
Issue opened in Penthouse repo
https://github.com/pocketjoso/penthouse/issues/204
