### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by XhmikosR** [addyosmani/critical#265]
@bezoerb: if you release a new version, can you also update the deps? There's a security warning for debug.

**Comment by bezoerb** [comment]
Looks like [`penthouse`](https://github.com/pocketjoso/penthouse) >= 1.2.0 returns minified css by default. If this is intended we need to remove the `--minify` option to make the tests green again because the resulting css will always be minified. From my perspective it would be totally fine to drop the minify option as the inlined css should be as small as possible.
@pocketjoso: Is this a feature or a bug? ;)

**Comment by pocketjoso** [comment]
@bezoerb It doesn't(fully)  _minify_ the css, but the [csstree parser](https://twitter.com/csstree) that penthouse 1.2 started using does trim some whitespace when turning the ~ ast back into a string, so that's what you're seeing.

You should still minify on top of this to get the smallest possible critical css.
