### ISSUE TITLE
giving .css file as src throws "css should not be empty" error

### ISSUE THREAD

**Issue by kanishk-anand-oyo** [addyosmani/critical#277]
I am trying to extract critical css from a .css file by listing is in src and giving an html page in the dest field, but it throws  `Unhandled rejection Error: css should not be empty` 
Any heads up?

**Comment by kanishk-anand-oyo** [comment]
I gave the css file in the css:[ ] array, but the program doesn't generate critical css if there isn't a css file in users.ejs
`const critical=require("critical");
critical.generate({
    base: 'public/stylesheets',
    src:'../../views/users.ejs',
    css:['public/stylesheets/users.css'],
    dest: '../../views/users.ejs',
    inline: true,
    extract: true,
    width: 800,
    height: 1100,
});`

My users.ejs is:

`<!DOCTYPE html>
<html>
<head>
    <title>users</title>
    <note no stylesheets referenced here>
</head>
<body>
 inside body =>some html here
</body>
</html>`



But as soon as I insert an irrelevant css file to users.ejs and run the same code for critical css, the program generates critical css of the file given in css:[ ] array . 
Any ideas how to run it without having to give an irrelevant css file.

**Comment by shervud** [comment]
Hi, I have also faced with the same problem. I contacted with Penthouse lib developer and he said that problem is on **critical** lib side.

An ugly issue "Unhandled rejection Error: css should not be empty" appears only on URLs whose <html> body does not have any css includings such as: `<link href="url-to-css.css" />`.

Some URLs implement css sources includings in the following way:
`<style>@import('url-to-css.css');</style>`
And it seems critical and penthouse modules libs ignore such files.

So, if some site has the next html:
```
<html>
<head>
<style>@import('http://example.com/styles/my-style.css');</style>
<link href="http://example.com/styles/my-prints.css" media="print" />
</head>
<body>...</body>
</html>
```

The critical will throw an error and will never work. While the following implementation will work and critical will be generated:

```
<html>
<head>
<link href="http://example.com/styles/my-style.css" media="all" />
<link href="http://example.com/styles/my-prints.css" media="print" />
</head>
<body>...</body>
</html>
```

p.s. Take in consideration, in 1st case there was <link />, but it does not work due to media="print" attribute.

**Comment by bezoerb** [comment]
We currently still don't support inline styles such as `<style>@import('http://example.com/styles/my-style.css');</style>` but it should work now with the css file passed as `css:['public/stylesheets/users.css']` when no `<link>` tag is present in the `<head>`
