### ISSUE TITLE
v1.3.2 not exiting properly

### ISSUE THREAD

**Issue by felipemsantana** [addyosmani/critical#309]
Using node v8.11.1

In v1.3.1:
```bash
➜ node -r 'critical' -e 'process.exitCode = 1' ; echo $?
1
```

In v1.3.2:
```bash
➜ node -r 'critical' -e 'process.exitCode = 1' ; echo $?
0
```

**Comment by billouboq** [comment]
Same here, using it with gulp and gulp says the task is done but it's not exiting

**Comment by billouboq** [comment]
It may be because puppeteer process does not exit properly.
I'm using this on a website with a lot of external scripts (ads, A/B testing, tags, monitoring, etc), so browser is always busy doing external ajax call and other thing so maybe it is blocking puppeteer from closing, just a thought.

Don't have time at work to review this properly, but will do if I find time.

**Comment by bezoerb** [comment]
This may be resulting from `async-exit-hook` which was introduced in v1.3.2
Until now this should be resolved in https://github.com/addyosmani/critical/pull/326

I'll add a test to make sure it stays that way ;)

**Comment by bezoerb** [comment]
Just published a new prerelease version. Would you mind trying?
You can install the new version with **npm i critical@next**

Thanks

**Comment by billouboq** [comment]
Thank you for this, unfortunately I'm not working on the project using it so I can't :/ but that's awesome anyway !

**Comment by bezoerb** [comment]
Closing this as we dropped the exit hooks completely in v2.
