### ISSUE TITLE
Find a way to offer the untouched critical CSS without prettier

### ISSUE THREAD

**Issue by XhmikosR** [addyosmani/critical#350]
Prettier fixes the formatting, but any issues that might arise from the minification process will still be there. Also, IMO this is an extra dependency.

So, this should be solved properly, without minifying the critical CSS in the first place, if `minify: false` is set.

**Comment by bezoerb** [comment]
@XhmikosR: penthouse only returns minified css so there's no other possibility on our side to return 'unminified' css as well. As far as i know we don't use any "unstable" minification features so there shouldn't be any issues on this side.
The `minify:false` option was only introduced for debugging purposes as the resulting critical css should be as small as possible ;)

If you need "untouched" critical css you might have to open a PR over at [`penthouse`](https://github.com/pocketjoso/penthouse)

**Comment by XhmikosR** [comment]
@bezoerb: I see your point, but on the other hand, getting compressed CSS and beautifying it here, adds an extra possible point of failure.

From a quick look I don't get how penthouse gives minified critical CSS; I don't see any CSS minifier in its dependencies, while I do see clean-css here.

**Comment by XhmikosR** [comment]
Also, I want to point out that the "safe" options you mention are not really the safest ones. You shouldn't use level 2 at all.

So, there must be an option for people to adjust this.

**Comment by pocketjoso** [comment]
Penthouse doesn't minimize the critical css explicitly, as you found @XhmikosR, it's just the way it comes out formatted from the AST library used, via [css-tree's generate function](https://github.com/csstree/csstree/blob/master/docs/generate.md). 

It was never my intention to put minification inside Penthouse - I always favoured having understandable output, and people using their own solution for minimisaiton, rather than baking it in, but when switching to this AST parser it was the default and I accepted it.

However I do see now that css-tree does offer to return a sourcemap, so in theory in should be possible to map that back to the original css. I'm still reluctant adding logic like that into penthouse, although depends on how much code it is. I also don't think I would want to make it the default as I think using the source maps will slow down Penthouse, but I'm open for it being an option.

@XhmikosR if you really want this I suggest you play around with it, and eventually open PR's to penthouse and/or critical.

**Comment by bezoerb** [comment]
I removed the minify option and the dependency to prettier. 
I don't think it's necessary to have unminified critical css.
@XhmikosR: Do you agree to close this one?

**Comment by XhmikosR** [comment]
Sure :)

**Comment by asipple1** [comment]
Using v4.0.1 went back to 3.1.0 to take advantage of `minify: false,`

We have a use case for un-minified critical CSS so it can pass PHP linting standards.
Also, discover the node_module clean-css is removing the last semicolon after the last property. 
Related issue https://github.com/clean-css/clean-css/pull/1091

**Comment by bezoerb** [comment]
@asipple1: Why don't you run prettier on the generated critical css after the critical job is finished? This should bring the exact same results as the `minify: false` option. I guess that you can't take advantage of inline-critical for inlining anyway when using php?
