### ISSUE TITLE
Is it possible to use Critical if your HTML files are rendered dynamically on the server?

### ISSUE THREAD

**Issue by nickarocho** [addyosmani/critical#375]
I am using Salesforce Commerce Cloud, which uses [ISML templates](https://documentation.b2c.commercecloud.salesforce.com/DOC2/index.jsp?topic=%2Fcom.demandware.dochelp%2FISML%2FISML.html) to dynamically generate the HTML on the server. Can I still use Critical if we don't have a target HTML file in the actual codebase? 

I would prefer not to have to manually inject/determine the critical CSS, but I can't find any documentation on how to do this or if anyone else has done this with similar templating like JSX or Handlebars.

Thank you in advance!

**Comment by nickarocho** [comment]
... Beuller?

**Comment by nickluger** [comment]
Seems to be a bad idea: https://github.com/addyosmani/critical/issues/359#issuecomment-470019922.

**Comment by XhmikosR** [comment]
AFAIK, no there isn't any way and it'll be slow anyway. This step is better done in the preprocessing stage.

**Comment by wildhart** [comment]
I've done this with Vue server side render in my Meteor app.  I only do it on my sales landing pages and I do it once during server boot up and cache the results so that I can instantly serve my landing pages with critical CSS.

Here's my explanatory post in the Meteor Forums: https://forums.meteor.com/t/pre-rendered-landing-pages-with-critical-css/50626

Requires at least `critical@2.0.0-14` with `rebase: false` as per #359.

Something similar should also work with other view layers, but you need to be able to do server side render to get the html string to pass to critical.  You also need to know the server location of your full css bundle.  It takes a about 20 seconds to pre-render 6 sales pages each at 5 screen dimensions

I'm really happy with the result.  I'd be even happier if I could pass multiple source html files so a new Chromium instance doesn't need to be created for each page as per #38, #111, #205, #215 and #320

**Comment by bezoerb** [comment]
@wildhart: commented in #111
