### ISSUE TITLE
Inlined <style> tags are not processed

### ISSUE THREAD

**Issue by SultanICQ** [addyosmani/critical#463]
Hi,

Is there a way to take into account all the inlined CSS?

For example, if the html web page only contains <style> tags and zero <link rel='stylesheets'> the extracted Critical CSS is empty.

Regards,

**Comment by bezoerb** [comment]
Hey @SultanICQ,
this is not possible right now. What do you want to achieve with the critical css when all the styles are already inlined?

**Comment by PeterKottas** [comment]
Imho, this is highly desirable. Lot of css in js or icon libraries put all sorts of styles in the head of the document while prerendering. It's reasonable to clean that up as part of build and only include the real critical css.

**Comment by PeterKottas** [comment]
Just as an example, leaving all inline styles for my index.html amounts to 133kb (total HTML size) while removing all inline styles and generating new critical (as combination of this libs output and handpicking the inline styles that are important), the HTML size goes down to 95kb. Also my critical styles are removed by code when the rendering is picked up by the framework and this way it's guaranteed not to get duplicate styles.

**Comment by bezoerb** [comment]
So you mean moving all inline styles to a separate file & only include the critical styles in the head. This could definitely safe some startup time.

**Comment by bezoerb** [comment]
Do you want to draft a PR for this?

**Comment by PeterKottas** [comment]
What I mean (and I think what this issue is about unless I am mistaken) is simply taking inline styles into consideration when generating critical css. 

In other words, if you have
```
<head>
<style>.red{background-color: red;}<style>
<link rel="stylesheet" type="text/css" href="blue.css">
</head>
```
where blue.css contains
```
.blue {
  background-color: blue;
}
```
and you put it through the critical, the output css won't contain the "red stuff", only the "blue stuff" will be included.

Since I am only getting css as output and inlining it myself, my usecase is pretty simple. I do all the style removal on my end. That being said, I think it could be implemented if somebody is generating whole HTML file. Doesn't matter if the css is inlined or referenced. The main idea remains the same. 

I am afraid I don't have time to contribute a pr for this at the moment. I could be convinced if we could get a company reference (backlink) in the readme but I am not sure if you would be willing to "ok" that , this being relatively small. Especially taking into consideration you don't have "clients" section in the readme. Anyways, this is who we are: https://guestbell.com/ and we contribute to open source fairly frequently (e.g.: https://github.com/react-page/react-page).

**Comment by bezoerb** [comment]
Thanks for clarifying @PeterKottas.
Added support for inline styles myself ;)

**Comment by PeterKottas** [comment]
Lovely @bezoerb . I missed this intially but nicely done. Thanks for putting in the work!
