### ISSUE TITLE
Images and Fonts url() path

### ISSUE THREAD

**Issue by solenoo** [addyosmani/critical#51]
Hi, my request is about the invalid url path that gets printed out after initialising the critical task. Here is an example of what I am referring to: Lets say I have a "background-image" with destination such as url('../img/someImage.jpg'). In the critical path this will look like url("/components/minified/img/someImage.jpg") which creates invalid request for the browser. The right output for the url should be url("../../public/components/minified/img/someImage.jpg"). My question is how can I get the right url, after starting the critical task ?

**Comment by bezoerb** [comment]
hey @solenoo, 
sorry for the late response.
The output you are getting from critical seems correct for your configuration.
We're rewriting assets paths to be absolute to your base directory.
`base: 'public/'` and an image path like `/public/components/minified/img/someImage.jpg` should result in `/components/minified/img/someImage.jpg` which should be fine assuming your docroot is pointing to the `public/` folder.

**Comment by bezoerb** [comment]
@solenoo Any progresses on this subject?
Thanks in advance.

**Comment by cormacmccarthy** [comment]
I'm having this same issue. Not sure if the circumstances are the same, but, I'll try and explain in case it helps:

* My app code resides in `/Package/Dynamic/` and compiles into `/Application/Dynamic/`. 
* My node server serves up everything inside of `/Application/Dynamic/` as `http://my.url.com/App/` (note how weird the "root" url of my app is, in that it is a subdirectory of the actual site. Before you judge, I have no control over this and agree that on the surface it seems stupid.  Try and think of it like `http://www.reddit.com/r/my-app` though and maybe it will seem more acceptable...)
* My `/Package/Dynamic/css/styles.css` file has a relative paths to `/Package/Dynamic/fonts/myfont.eot` (& .svg, etc). 
* When it gets digested by critical, my font paths turn into `/fonts/myfont.eot` instead of `fonts/myfont.eot`. 

So, there's the problem. Instead of looking for the fonts in `http://my.url.com/App/` it is looking for them in `http://my.url.com/` because of the absolute pathing. If there was some `url` option that I could pass `http://my.url.com/App/` into to inform critical of the _actual_ absolute path, I'd do that. Or, if there was some way to say "don't prepend relative paths with `/`" I'd do that too.

Hope this helps, thanks! Also: I'm using grunt-critical (in case it matters)

**Comment by cormacmccarthy** [comment]
Looks like this may be the culprit:

https://github.com/addyosmani/critical/blob/master/index.js#L150

I'm going to try changing that locally and seeing if it does what I want.

**Comment by bezoerb** [comment]
wow,... that root url is really weird ;) I'm not quite sure i got this right.
So your docroot is more like a symlink to a real folder on your server but without a symlink. So you got no folder like `/App` which we could use to compute the asset path.
I'm not quite sure but i think there was a good reason to make this path absolute. I'll think this over again and maybe there's a chance to compute relative paths. Otherwise we could provide some option to configure a path prefix.
@addyosmani any thoughts?

**Comment by cormacmccarthy** [comment]
Correct, there is no folder like /App that we could use to compute the asset path.

The production server is neither controlled by me nor available to me. Not only that, but, I'm not easily able to change the structure of the project itself (as I'm basically a contractor working with a team specifically for initial page-load speed/optimizations).

Thanks!

**Comment by bezoerb** [comment]
I think a `pathPrefix` option would be the most robust solution to this issue.

**Comment by cormacmccarthy** [comment]
Ok, here's both. If you want me to issue a PR, let me know which one you'd like. Thanks!

```Javascript
                    var pathPrefix = (typeof opts.pathPrefix === "undefined") ? "/" : opts.pathPrefix;
                    return normalizePath(match.replace(filePath, path.join(pathPrefix, relativeToBase)));
```

```Javascript
                    // prepend / to make it absolute
                    if (typeof opts.useRelativePaths === "undefined" || opts.useRelativePaths === false) {
                        relativeToBase = path.join('/', relativeToBase);
                    }

                    return normalizePath(match.replace(filePath, relativeToBase));
```

**Comment by bezoerb** [comment]
I would go for the first one as using a path relative to baseDir will fail as soon as you are serving document from e.g. `/App/Controller/some.html`.
