### ISSUE TITLE
Minify option

### ISSUE THREAD

**Issue by thejimbirch** [addyosmani/critical#522]
Looks like the Minify option was removed during some other work in #350 and now, all the Critical CSS is minified.

Using Critical in combination with the Drupal CMS, the generated files do not meet Drupal coding standards. The Drupal coding standards do not allow for minified files.  Drupal core itself concatenates and minifies CSS and JavaScript as part of the page build.

Would it be possible to add the minfy option back?

cc @asipple

**Comment by bezoerb** [comment]
Hey @thejimbirch, 
the removal of the `minify` option was intended as it was only kind of a hack using prettier because there's no way to receive the unminified css from penthouse (the library doing all the work in computing the critical css). Running prettier on the critical css should not be a part of critical as this could easily be implemented as a postprocess step after critical in the build pipeline.

Sorry ;)

As you're using PHP it should be
