### ISSUE TITLE
Critical removes dots in url path

### ISSUE THREAD

**Issue by tictac22** [addyosmani/critical#524]
I don't know why, but Critical removes dots in urls and it breaks all connecting images and fonts
Example:
Before
![image](https://user-images.githubusercontent.com/70350446/147706020-7805dd50-f66d-4009-a52b-d08e3fa983ce.png)
After
![image](https://user-images.githubusercontent.com/70350446/147705990-2a61f710-fe93-447e-887e-4b664485565b.png)

**Comment by tictac22** [comment]
P.S and example with fonts
Before:
![image](https://user-images.githubusercontent.com/70350446/147706350-00824ee4-2c5f-407b-accc-caf230de5668.png)

After:
![image](https://user-images.githubusercontent.com/70350446/147706406-23716a76-b146-4075-8130-0e03e569bcf5.png)

**Comment by bezoerb** [comment]
Hey @tictac22,
this is kind of intended as we need to rebase the urls in the css to the location of the html file. Imagine you have a directory structure like this:
```bash
.
├── index.html
├── css
│   └── main.css
└── fonts
    └── OpenSans-Bold.woff
```

The url `../fonts/OpenSans-Bold.woff` is relative to your css file but when the critical CSS is inlined we need to access the fonts from `fonts/OpenSans-Bold.woff` because the browser won't find the file otherwise when trying to locate it relative to the html file.

The automatic rebase should work as expected for most configurations. You can try setting the `base` directory (docroot) or you can tweak the rebase by [setting a custom `rebase` option](https://github.com/addyosmani/critical#generate-critical-path-css-and-specify-asset-rebase-behaviour)

**Comment by tictac22** [comment]
Thanks for explanation, it never crossed my mind. To solve the question I just moved my uncritical css at the same level with index.html and now all works
